### ISSUE TITLE
脚本运行后，结果打不开，个别工程脚本运行卡死

### ISSUE THREAD

**Issue by Nemostar1989** [EyreFree/EFPodsAnalyzer#4]
### Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

- [ ] I have read the [README.md](https://github.com/EyreFree/EFPodsAnalyzer/blob/master/README.md), but there is no information I need.
- [ ] I have searched in [existing issues](https://github.com/EyreFree/EFPodsAnalyzer/issues?utf8=%E2%9C%93&q=is%3Aissue), but did find a same one.

#### Description

[Tell us about the issue]

#### Reproduce

[The steps to reproduce this issue. What are the parameters, where did you put your code, etc.]

#### Other Comment

[Add anything else here]

**Comment by EyreFree** [comment]
这么可怕的么...

大佬是否方便提供下 `Podfile.lock` 以供分析？

**Comment by Nemostar1989** [comment]
直接使用的示例项目， 脚本运行后卡死。
python 版本为2.7.10

**Comment by EyreFree** [comment]
@Nemostar1989 

经检测，部分 JS 依赖需要翻墙，现已放到本地，可重试下

**Comment by Nemostar1989** [comment]
3Q 晚点试了给你回复

**Comment by Nemostar1989** [comment]
还是不行啊~方便加个QQ或者微信调试吗？QQ 460496300 微信 lm4413000

**Comment by EyreFree** [comment]
@Nemostar1989 已修正
