### ISSUE TITLE
小建议：期望在依赖线上增加方向箭头

### ISSUE THREAD

**Issue by rakeyang** [EyreFree/EFPodsAnalyzer#5]
### Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

- [ ] I have read the [README.md](https://github.com/EyreFree/EFPodsAnalyzer/blob/master/README.md), but there is no information I need.
- [ ] I have searched in [existing issues](https://github.com/EyreFree/EFPodsAnalyzer/issues?utf8=%E2%9C%93&q=is%3Aissue), but did find a same one.

#### Description

目前：鼠标放到依赖线上能知道依赖指向，但是不怎么方便
期望：在依赖线上能增加指向的箭头一幕了然，而不需要手表放上去，更加方便排查不合理依赖，交叉依赖等等问题

谢谢大佬提供的工具👍

附件提供我的依赖图数据
[EFPADiagram.zip](https://github.com/EyreFree/EFPodsAnalyzer/files/4302717/EFPADiagram.zip)

#### Reproduce

[The steps to reproduce this issue. What are the parameters, where did you put your code, etc.]

#### Other Comment

[Add anything else here]

**Comment by EyreFree** [comment]
唔，图表用的第三方，不是很会改样式，有时间我研究一下，[捂脸]

**Comment by rakeyang** [comment]
在Podfile同目录中执行没办法读取到EFPAConfig.json文件

**Comment by EyreFree** [comment]
> 在Podfile同目录中执行没办法读取到EFPAConfig.json文件

能稳定复现么？我刚测了一下最新版本是好的

**Comment by Hackice** [comment]
可以配置`edgeSymbol: ['none', 'arrow']`实现上述效果
My PR: https://github.com/EyreFree/EFPodsAnalyzer/pull/6
参考文档：[series-graph.edgeSymbol](https://echarts.apache.org/zh/option.html#series-graph.edgeSymbol)

**Comment by EyreFree** [comment]
[0.2.6](https://github.com/EyreFree/EFPodsAnalyzer/releases/tag/0.2.6) 已实现.

@Hackice 感谢 PR.
